#!/usr/bin/env python3
"""Build a local, inspectable ModelBake release candidate without publishing it."""

from __future__ import annotations

import argparse
import email.parser
import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import urllib.parse
import venv
import zipfile
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_STAGE = ROOT / "release-staging"
STAGE_MARKER = ".modelbake-release-stage"
STAGE_MARKER_CONTENT = "modelbake release staging v1\n"
EXPECTED_SITE_SCHEMA = "modelbake.site-evidence.v1"
EXPECTED_RUN_SCHEMA = "modelbake.run.v1"
EXPECTED_NODE_COUNT = 7
REPRODUCIBLE_BUILD_EPOCH = "315532800"  # 1980-01-01, valid for ZIP and tar.


class ReleaseCheckError(RuntimeError):
    """A release invariant or command failed."""


@dataclass(frozen=True)
class CommandResult:
    stdout: str
    stderr: str


class _AssetParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.references: list[str] = []
        self.has_doctype = False
        self.has_html = False
        self.has_title = False
        self.has_viewport = False
        self.has_main = False

    def handle_decl(self, decl: str) -> None:
        if decl.lower().strip() != "doctype html":
            raise ReleaseCheckError(f"unexpected HTML declaration: {decl}")
        self.has_doctype = True

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        values = dict(attrs)
        if tag == "html":
            self.has_html = bool(values.get("lang"))
        elif tag == "title":
            self.has_title = True
        elif tag == "main":
            self.has_main = True
        elif tag == "meta" and values.get("name") == "viewport":
            self.has_viewport = bool(values.get("content"))
        for attribute in ("src", "href", "poster"):
            value = values.get(attribute)
            if value:
                self.references.append(value)


_FORBIDDEN_PUBLIC_CLAIMS = (
    "certified safe",
    "works everywhere",
    "guaranteed compatible",
    "production-ready",
    "model quality preserved",
)
_LONG_HEX_RE = re.compile(
    r"(?<![0-9a-f])(?:sha256:)?[0-9a-f]{32,}(?![0-9a-f])", re.IGNORECASE
)


def _visible_html_text(content: str) -> str:
    without_code = re.sub(
        r"<(script|style)\b[^>]*>.*?</\1>",
        " ",
        content,
        flags=re.IGNORECASE | re.DOTALL,
    )
    return " ".join(re.sub(r"<[^>]+>", " ", without_code).split()).lower()


def _validate_public_claims(path: Path, content: str) -> None:
    lowered = content.lower()
    for phrase in _FORBIDDEN_PUBLIC_CLAIMS:
        if phrase in lowered:
            raise ReleaseCheckError(
                f"broad public claim is forbidden in {path.name}: {phrase}"
            )
    if _LONG_HEX_RE.search(content):
        raise ReleaseCheckError(
            f"hardcoded long run ID or digest is forbidden in {path.name}; render evidence JSON"
        )


def _validate_evidence_page_claims(path: Path, content: str) -> None:
    visible = _visible_html_text(content)
    publisher = visible.find("generated by the publisher")
    independent = visible.find("not an independent attestation")
    if publisher < 0 or independent < 0 or abs(publisher - independent) > 240:
        raise ReleaseCheckError(
            "real-evidence.html must visibly say the record is publisher-generated, "
            "not independent attestation"
        )
    if "the model was not certified" not in visible:
        raise ReleaseCheckError(
            "real-evidence.html must visibly say the model was not certified"
        )
    for phrase in (
        "publisher-generated cas acceptance",
        "receipt-backed baseline decision",
        "records no actor identity or authorization",
    ):
        if phrase not in visible:
            raise ReleaseCheckError(
                f"real-evidence.html must visibly preserve its CAS boundary: {phrase}"
            )
    if (
        re.search(
            r"<script\b[^>]*\bsrc=[\"']\./evidence\.js[\"']",
            content,
            re.IGNORECASE,
        )
        is None
    ):
        raise ReleaseCheckError("real-evidence.html must load evidence.js")


def _validate_index_claims(path: Path, content: str) -> None:
    visible = _visible_html_text(content)
    release = visible.find("release record")
    publisher = visible.find("publisher acceptance")
    if release < 0 or publisher < 0 or abs(release - publisher) > 600:
        raise ReleaseCheckError(
            "index.html must label its release record as publisher acceptance"
        )
def _say(message: str) -> None:
    print(f"[release-check] {message}", flush=True)


def run_command(
    argv: Sequence[str | os.PathLike[str]],
    *,
    cwd: Path = ROOT,
    env: dict[str, str] | None = None,
    label: str | None = None,
    timeout_seconds: int = 600,
) -> CommandResult:
    """Run one argv-only command and retain useful output on failure."""

    command = [os.fspath(item) for item in argv]
    if not command or not command[0]:
        raise ReleaseCheckError("refusing to run an empty command")
    _say(label or f"run: {' '.join(command)}")
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            env=env,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
    except subprocess.TimeoutExpired as exc:
        raise ReleaseCheckError(
            f"command timed out after {timeout_seconds}s: {command!r}"
        ) from exc
    except OSError as exc:
        raise ReleaseCheckError(f"could not start {command[0]}: {exc}") from exc
    if completed.stdout:
        print(completed.stdout, end="" if completed.stdout.endswith("\n") else "\n")
    if completed.stderr:
        print(
            completed.stderr,
            end="" if completed.stderr.endswith("\n") else "\n",
            file=sys.stderr,
        )
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout).strip()
        suffix = f": {detail[-1000:]}" if detail else ""
        raise ReleaseCheckError(
            f"command failed with exit {completed.returncode}: {command!r}{suffix}"
        )
    return CommandResult(completed.stdout, completed.stderr)


def prepare_stage(stage: Path) -> Path:
    """Reset only a directory carrying our exact marker; refuse unknown contents."""

    expanded = stage.expanduser()
    if expanded.is_symlink():
        raise ReleaseCheckError(f"staging directory may not be a symlink: {expanded}")
    target = expanded.resolve()
    forbidden = {Path(target.anchor), ROOT, ROOT.parent, Path.home().resolve()}
    if target in forbidden:
        raise ReleaseCheckError(f"unsafe staging directory: {target}")
    marker = target / STAGE_MARKER
    if target.exists():
        if not target.is_dir():
            raise ReleaseCheckError(f"staging path is not a directory: {target}")
        children = list(target.iterdir())
        if children:
            try:
                marker_value = marker.read_text(encoding="utf-8")
            except OSError as exc:
                raise ReleaseCheckError(
                    f"refusing to clear unmarked staging directory: {target}"
                ) from exc
            if marker_value != STAGE_MARKER_CONTENT:
                raise ReleaseCheckError(f"invalid staging marker in {target}")
            for child in children:
                if child.is_symlink() or child.is_file():
                    child.unlink()
                elif child.is_dir():
                    shutil.rmtree(child)
                else:
                    raise ReleaseCheckError(f"unsupported staging entry: {child}")
    target.mkdir(parents=True, exist_ok=True)
    marker.write_text(STAGE_MARKER_CONTENT, encoding="utf-8")
    return target


def _local_reference(reference: str) -> str | None:
    parsed = urllib.parse.urlsplit(reference)
    if parsed.scheme or parsed.netloc or not parsed.path or parsed.path.startswith("#"):
        return None
    return urllib.parse.unquote(parsed.path)


def _resolve_asset(site_dir: Path, document: Path, reference: str) -> Path | None:
    local = _local_reference(reference)
    if local is None:
        return None
    candidate = (document.parent / local).resolve()
    try:
        candidate.relative_to(site_dir.resolve())
    except ValueError as exc:
        raise ReleaseCheckError(
            f"asset escapes site directory: {document.name} -> {reference}"
        ) from exc
    return candidate


def validate_site(
    site_dir: Path,
    *,
    javascript_checker: Callable[[Path], None] | None = None,
    validate_real_evidence: bool = True,
) -> list[Path]:
    """Validate static HTML, referenced assets, JSON, and JavaScript files."""

    root = site_dir.resolve()
    index = root / "index.html"
    if not index.is_file():
        raise ReleaseCheckError(f"missing site entry point: {index}")
    assets: set[Path] = {index}
    pending_documents = [index]
    checked_documents: set[Path] = set()
    while pending_documents:
        document = pending_documents.pop()
        if document in checked_documents:
            continue
        checked_documents.add(document)
        try:
            html_text = document.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise ReleaseCheckError(f"cannot read site HTML {document.name}: {exc}") from exc
        parser = _AssetParser()
        try:
            parser.feed(html_text)
            parser.close()
        except (ValueError, ReleaseCheckError) as exc:
            raise ReleaseCheckError(f"invalid site HTML {document.name}: {exc}") from exc
        missing_semantics = [
            name
            for present, name in (
                (parser.has_doctype, "HTML5 doctype"),
                (parser.has_html, "<html lang>"),
                (parser.has_title, "<title>"),
                (parser.has_viewport, "viewport meta"),
                (parser.has_main, "<main>"),
            )
            if not present
        ]
        if missing_semantics:
            raise ReleaseCheckError(
                f"site HTML {document.name} is missing: {', '.join(missing_semantics)}"
            )
        _validate_public_claims(document, html_text)
        if document.name == "real-evidence.html":
            _validate_evidence_page_claims(document, html_text)
        elif document.name == "index.html":
            _validate_index_claims(document, html_text)
        for reference in parser.references:
            asset = _resolve_asset(root, document, reference)
            if asset is not None:
                if not asset.is_file():
                    raise ReleaseCheckError(
                        f"missing referenced site asset: {document.name} -> {reference}"
                    )
                assets.add(asset)
                if asset.suffix.lower() == ".html":
                    pending_documents.append(asset)

    for stylesheet in sorted(asset for asset in assets if asset.suffix == ".css"):
        try:
            css_text = stylesheet.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise ReleaseCheckError(
                f"cannot read stylesheet {stylesheet.name}: {exc}"
            ) from exc
        for match in re.finditer(r"url\(\s*(['\"]?)(.*?)\1\s*\)", css_text):
            asset = _resolve_asset(root, stylesheet, match.group(2))
            if asset is not None:
                if not asset.is_file():
                    raise ReleaseCheckError(
                        f"missing stylesheet asset: {stylesheet.name} -> {match.group(2)}"
                    )
                assets.add(asset)

    json_files = sorted(root.rglob("*.json"))
    if not json_files:
        raise ReleaseCheckError("site contains no JSON evidence")
    for path in json_files:
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeError, json.JSONDecodeError) as exc:
            raise ReleaseCheckError(f"invalid site JSON {path.name}: {exc}") from exc
        if path.name == "demo-evidence.json":
            _validate_site_evidence(payload, path)
        elif path.name == "real-evidence.json":
            if validate_real_evidence:
                _validate_real_evidence(payload, path)
        elif path.name == "comparison-evidence.json":
            _validate_comparison_evidence(payload, path)
        assets.add(path)

    javascript_files = sorted(root.rglob("*.js"))
    if not javascript_files:
        raise ReleaseCheckError("site contains no JavaScript")
    if javascript_checker is None:
        raise ReleaseCheckError("JavaScript validation is unavailable")
    for path in javascript_files:
        try:
            javascript_text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeError) as exc:
            raise ReleaseCheckError(f"cannot read JavaScript {path.name}: {exc}") from exc
        _validate_public_claims(path, javascript_text)
        javascript_checker(path)
        assets.add(path)
    return sorted(assets)


def _validate_real_evidence(payload: Any, path: Path) -> None:
    if not isinstance(payload, dict) or payload.get("schema") != "modelbake.public-acceptance.v2":
        raise ReleaseCheckError(f"unexpected real evidence schema in {path.name}")
    acceptance = payload.get("acceptance")
    expected_fields = {
        "kind",
        "channel",
        "decision_digest",
        "review_digest",
        "candidate_manifest_digest",
        "predecessor_decision_digest",
        "comparison_digest",
    }
    if not isinstance(acceptance, dict) or set(acceptance) != expected_fields:
        raise ReleaseCheckError(
            f"real evidence in {path.name} lacks the exact CAS acceptance binding"
        )
    if acceptance["kind"] != "publisher-generated-cas-acceptance":
        raise ReleaseCheckError(f"real evidence in {path.name} has an invalid acceptance kind")
    if (
        not isinstance(acceptance["channel"], str)
        or re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,63}", acceptance["channel"])
        is None
    ):
        raise ReleaseCheckError(f"real evidence in {path.name} has an invalid channel")
    for field in expected_fields - {"kind", "channel"}:
        if (
            not isinstance(acceptance[field], str)
            or re.fullmatch(r"sha256:[0-9a-f]{64}", acceptance[field]) is None
        ):
            raise ReleaseCheckError(
                f"real evidence in {path.name} has an invalid {field}"
            )
    warm = payload.get("warm_run")
    warm_manifest = warm.get("manifest") if isinstance(warm, dict) else None
    if (
        not isinstance(warm_manifest, dict)
        or warm_manifest.get("modelbake_digest")
        != acceptance["candidate_manifest_digest"]
    ):
        raise ReleaseCheckError(
            f"real evidence in {path.name} does not bind acceptance to the warm manifest"
        )


def validate_public_evidence(
    evidence: Path,
    archives: Iterable[Path],
    env: dict[str, str],
) -> None:
    """Require receipt-backed v2 evidence bound to exact staged distributions."""

    if evidence.is_symlink() or not evidence.is_file():
        raise ReleaseCheckError(
            f"missing public real acceptance evidence: {evidence}; "
            "use --bootstrap-real-acceptance only to prepare its exact packages"
        )
    archive_paths = list(archives)
    wheels = [path for path in archive_paths if path.suffix == ".whl"]
    sdists = [path for path in archive_paths if path.name.endswith(".tar.gz")]
    if len(wheels) != 1 or len(sdists) != 1:
        raise ReleaseCheckError("public evidence requires exactly one wheel and one sdist")
    run_command(
        [
            sys.executable,
            ROOT / "scripts" / "generate_public_evidence.py",
            "--validate-public",
            evidence,
            "--wheel",
            wheels[0],
            "--sdist",
            sdists[0],
        ],
        env=env,
        label="validate public real acceptance evidence against staged packages",
    )


def _validate_comparison_evidence(payload: Any, path: Path) -> None:
    if not isinstance(payload, dict) or payload.get("schema") != "modelbake.public-comparison.v1":
        raise ReleaseCheckError(f"unexpected comparison evidence schema in {path.name}")
    obsolete_fields = {"artifact_bytes", "source_bytes_same"}

    def find_obsolete(value: Any) -> set[str]:
        if isinstance(value, dict):
            found = obsolete_fields.intersection(value)
            for child in value.values():
                found.update(find_obsolete(child))
            return found
        if isinstance(value, list):
            found: set[str] = set()
            for child in value:
                found.update(find_obsolete(child))
            return found
        return set()

    obsolete = sorted(find_obsolete(payload))
    if obsolete:
        raise ReleaseCheckError(f"comparison evidence uses obsolete fields: {obsolete}")
    if payload.get("fixture_only") is not True:
        raise ReleaseCheckError("public comparison evidence must retain its fixture-only label")
    lineage = payload.get("lineage")
    if not isinstance(lineage, dict) or not isinstance(
        lineage.get("source_digest_same"), bool
    ):
        raise ReleaseCheckError("fixture comparison must record source_digest_same")
    counts = payload.get("counts")
    if not isinstance(counts, dict) or counts.get("reused_from_cache") != 4 or counts.get("added") != 2:
        raise ReleaseCheckError("fixture comparison must record four reuses and two additions")
    nodes = payload.get("nodes")
    if not isinstance(nodes, list) or not nodes:
        raise ReleaseCheckError("fixture comparison must contain node records")
    for index, node in enumerate(nodes):
        if not isinstance(node, dict) or node.get("recorded_output_digests") not in {
            "same",
            "changed",
            "added",
            "removed",
        }:
            raise ReleaseCheckError(
                f"fixture comparison nodes[{index}] must record output-digest status"
            )
    if payload.get("truth_boundary") is None or "not GGUF" not in payload["truth_boundary"]:
        raise ReleaseCheckError("fixture comparison must state its GGUF boundary")


def _validate_site_evidence(payload: Any, path: Path) -> None:
    if not isinstance(payload, dict) or payload.get("schema") != EXPECTED_SITE_SCHEMA:
        raise ReleaseCheckError(f"unexpected evidence schema in {path.name}")
    for field in ("run_id", "project", "runner"):
        if not isinstance(payload.get(field), str) or not payload[field]:
            raise ReleaseCheckError(f"evidence has no recorded {field}")
    for field in ("recipe_digest", "source_digest"):
        if not isinstance(payload.get(field), str) or re.fullmatch(
            r"sha256:[0-9a-f]{64}", payload[field]
        ) is None:
            raise ReleaseCheckError(f"evidence has no recorded {field}")
    nodes = payload.get("nodes")
    if not isinstance(nodes, list) or len(nodes) != EXPECTED_NODE_COUNT:
        raise ReleaseCheckError(f"evidence must contain {EXPECTED_NODE_COUNT} nodes")
    repeat = payload.get("repeat_run")
    if (
        not isinstance(repeat, dict)
        or repeat.get("same_inputs") is not True
        or repeat.get("digest_verified_cache_hits") != 7
        or not isinstance(repeat.get("run_id"), str)
        or not repeat["run_id"]
    ):
        raise ReleaseCheckError("evidence repeat run must record seven cache hits")
    expected_nodes = {
        "source": ("source", "produced"),
        "f16": ("convert", "produced"),
        "q4": ("quantize", "produced"),
        "q8": ("quantize", "produced"),
        "run-f16": ("smoke", "fixture_observed"),
        "run-q4": ("smoke", "fixture_observed"),
        "run-q8": ("smoke", "fixture_observed"),
    }
    node_ids: set[str] = set()
    for index, node in enumerate(nodes):
        if not isinstance(node, dict):
            raise ReleaseCheckError(f"evidence nodes[{index}] is not an object")
        node_id = node.get("id")
        if not isinstance(node_id, str) or not node_id or node_id in node_ids:
            raise ReleaseCheckError(f"evidence nodes[{index}] has an invalid id")
        node_ids.add(node_id)
        expected = expected_nodes.get(node_id)
        if expected is None or (node.get("kind"), node.get("state")) != expected:
            raise ReleaseCheckError(f"evidence nodes[{index}] has invalid kind or state")
        if node["kind"] == "smoke":
            if not isinstance(node.get("tokens_observed"), int) or node[
                "tokens_observed"
            ] < 1:
                raise ReleaseCheckError(f"evidence nodes[{index}] has invalid tokens")
        elif not isinstance(node.get("bytes"), int) or node["bytes"] < 1:
            raise ReleaseCheckError(f"evidence nodes[{index}] has invalid byte size")
        digest = node.get("digest")
        if (
            not isinstance(digest, str)
            or re.fullmatch(r"sha256:[0-9a-f]{64}", digest) is None
        ):
            raise ReleaseCheckError(f"evidence nodes[{index}] has no SHA-256 digest")
    if node_ids != set(expected_nodes):
        raise ReleaseCheckError("evidence does not contain the expected fixture node set")
    exclusions = payload.get("exclusions")
    if not isinstance(exclusions, list) or len(exclusions) < 3:
        raise ReleaseCheckError("fixture evidence must publish explicit exclusions")


def _load_successful_manifest(path: Path, *, warm: bool) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ReleaseCheckError(f"cannot read run manifest {path}: {exc}") from exc
    if not isinstance(data, dict) or data.get("schema") != EXPECTED_RUN_SCHEMA:
        raise ReleaseCheckError(f"unexpected run manifest schema in {path}")
    if data.get("status") != "succeeded":
        raise ReleaseCheckError(f"run did not succeed: {path}")
    nodes = data.get("nodes")
    if not isinstance(nodes, list) or len(nodes) != EXPECTED_NODE_COUNT:
        raise ReleaseCheckError(f"run must contain {EXPECTED_NODE_COUNT} nodes: {path}")
    states = [node.get("state") if isinstance(node, dict) else None for node in nodes]
    if warm:
        if states != ["cache_hit"] * EXPECTED_NODE_COUNT:
            raise ReleaseCheckError(f"warm run was not entirely cache-backed: {states}")
    elif states.count("produced") != 4 or states.count("fixture_observed") != 3:
        raise ReleaseCheckError(
            "cold run must contain four produced and three fixture-observed nodes: "
            f"{states}"
        )
    return data


def _parse_command_json(result: CommandResult, label: str) -> dict[str, Any]:
    try:
        payload = json.loads(result.stdout)
    except (TypeError, json.JSONDecodeError) as exc:
        raise ReleaseCheckError(f"{label} did not return JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise ReleaseCheckError(f"{label} did not return a JSON object")
    return payload


def _require_warm_comparison(payload: dict[str, Any], label: str) -> None:
    counts = payload.get("counts")
    lineage = payload.get("lineage")
    nodes = payload.get("nodes")
    if payload.get("schema") != "modelbake.compare.v1":
        raise ReleaseCheckError(f"{label} returned an unexpected comparison schema")
    if not isinstance(counts, dict) or counts.get("reused_from_cache") != EXPECTED_NODE_COUNT:
        raise ReleaseCheckError(f"{label} did not record seven cache reuses")
    if not isinstance(lineage, dict) or lineage.get("source_digest_same") is not True:
        raise ReleaseCheckError(f"{label} did not retain the recorded source digest")
    if not isinstance(nodes, list) or any(
        not isinstance(node, dict) or node.get("recorded_output_digests") != "same"
        for node in nodes
    ):
        raise ReleaseCheckError(f"{label} did not retain recorded output digests")


def _load_story_manifest(path: Path, *, candidate: bool) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ReleaseCheckError(f"cannot read installed story manifest {path}: {exc}") from exc
    nodes = payload.get("nodes") if isinstance(payload, dict) else None
    expected_ids = {
        "source",
        "convert-f16-base",
        "quantize-q4",
        "smoke-q4",
    }
    if candidate:
        expected_ids |= {"quantize-q8", "smoke-q8"}
    if (
        payload.get("schema") != EXPECTED_RUN_SCHEMA
        or payload.get("status") != "succeeded"
        or not isinstance(nodes, list)
        or {node.get("id") for node in nodes if isinstance(node, dict)} != expected_ids
    ):
        raise ReleaseCheckError(f"installed demo story has unexpected nodes: {path}")
    states = {node["id"]: node["state"] for node in nodes}
    if candidate:
        if any(states[node_id] != "cache_hit" for node_id in expected_ids - {"quantize-q8", "smoke-q8"}):
            raise ReleaseCheckError("candidate story did not reuse all baseline nodes")
        if states["quantize-q8"] != "produced" or states["smoke-q8"] != "fixture_observed":
            raise ReleaseCheckError("candidate story did not add fresh Q8 evidence")
    elif list(states.values()).count("produced") != 3 or list(states.values()).count(
        "fixture_observed"
    ) != 1:
        raise ReleaseCheckError("baseline story did not produce its four expected nodes")
    return payload


def _require_story_comparison(payload: dict[str, Any], label: str) -> None:
    counts = payload.get("counts")
    if (
        payload.get("schema") != "modelbake.compare.v1"
        or not isinstance(counts, dict)
        or counts.get("reused_from_cache") != 4
        or counts.get("added") != 2
    ):
        raise ReleaseCheckError(f"{label} did not show Q4 to Q4+Q8 expansion")


def _output_bytes(path: Path) -> int:
    """Measure regular output bytes without following links or accepting special files."""

    try:
        info = path.lstat()
    except OSError as exc:
        raise ReleaseCheckError(f"cannot inspect fixture output {path}: {exc}") from exc
    if stat.S_ISREG(info.st_mode):
        return info.st_size
    if not stat.S_ISDIR(info.st_mode):
        raise ReleaseCheckError(f"fixture output is not a regular file or directory: {path}")
    total = 0
    try:
        for child in path.rglob("*"):
            child_info = child.lstat()
            if stat.S_ISDIR(child_info.st_mode):
                continue
            if not stat.S_ISREG(child_info.st_mode):
                raise ReleaseCheckError(f"fixture output contains an unsafe path: {child}")
            total += child_info.st_size
    except OSError as exc:
        raise ReleaseCheckError(f"cannot measure fixture output {path}: {exc}") from exc
    return total


def _atomic_write_json(destination: Path, payload: dict[str, Any]) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{destination.name}.", suffix=".tmp", dir=destination.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(
                (json.dumps(payload, indent=2, sort_keys=False) + "\n").encode("utf-8")
            )
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, destination)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def generate_demo_evidence(
    cold_manifest: Path, warm_manifest: Path, destination: Path
) -> dict[str, Any]:
    """Derive the public fixture record from verified acceptance manifests."""

    cold = _load_successful_manifest(cold_manifest, warm=False)
    warm = _load_successful_manifest(warm_manifest, warm=True)
    cold_nodes = {node["id"]: node for node in cold["nodes"]}
    warm_nodes = {node["id"]: node for node in warm["nodes"]}
    if set(cold_nodes) != set(warm_nodes):
        raise ReleaseCheckError("warm fixture nodes do not match the cold run")
    for node_id, cold_node in cold_nodes.items():
        if warm_nodes[node_id].get("output_digests") != cold_node.get("output_digests"):
            raise ReleaseCheckError(
                f"warm fixture output digests changed for node {node_id!r}"
            )
    for field in ("project", "recipe_digest", "source_digest"):
        if warm.get(field) != cold.get(field):
            raise ReleaseCheckError(f"warm fixture changed recorded {field}")

    ui_ids = {
        "source": "source",
        "convert-f16": "f16",
        "quantize-q4": "q4",
        "quantize-q8": "q8",
        "smoke-f16": "run-f16",
        "smoke-q4": "run-q4",
        "smoke-q8": "run-q8",
    }
    if set(cold_nodes) != set(ui_ids):
        raise ReleaseCheckError(
            f"fixture node set cannot be mapped to public evidence: {sorted(cold_nodes)}"
        )
    public_nodes: list[dict[str, Any]] = []
    runner_names: set[str] = set()
    for node in cold["nodes"]:
        outputs = node.get("outputs")
        digests = node.get("output_digests")
        observations = node.get("observations")
        if (
            not isinstance(outputs, dict)
            or len(outputs) != 1
            or not isinstance(digests, dict)
            or len(digests) != 1
            or set(outputs) != set(digests)
            or not isinstance(observations, dict)
        ):
            raise ReleaseCheckError(f"fixture node {node['id']!r} has invalid outputs")
        output_name = next(iter(outputs))
        runner = observations.get("runner")
        if not isinstance(runner, str) or not runner:
            raise ReleaseCheckError(f"fixture node {node['id']!r} has no runner record")
        runner_names.add(runner)
        public_node: dict[str, Any] = {
            "id": ui_ids[node["id"]],
            "kind": node["kind"],
            "state": node["state"],
        }
        if node["kind"] == "smoke":
            tokens = observations.get("tokens_observed")
            if not isinstance(tokens, int) or tokens < 1:
                raise ReleaseCheckError(
                    f"fixture smoke node {node['id']!r} has invalid token evidence"
                )
            public_node["tokens_observed"] = tokens
        else:
            measured_bytes = _output_bytes(Path(outputs[output_name]))
            recorded_bytes = observations.get("bytes")
            if recorded_bytes is not None and recorded_bytes != measured_bytes:
                raise ReleaseCheckError(
                    f"fixture node {node['id']!r} byte count changed"
                )
            public_node["bytes"] = measured_bytes
        public_node["digest"] = digests[output_name]
        public_nodes.append(public_node)
    if len(runner_names) != 1:
        raise ReleaseCheckError("fixture nodes do not share one recorded runner")

    payload = {
        "schema": EXPECTED_SITE_SCHEMA,
        "source": "generated from verified local ModelBake fixture acceptance",
        "run_id": cold["run_id"],
        "project": cold["project"],
        "recipe_digest": cold["recipe_digest"],
        "source_digest": cold["source_digest"],
        "runner": next(iter(runner_names)),
        "repeat_run": {
            "run_id": warm["run_id"],
            "same_inputs": True,
            "digest_verified_cache_hits": EXPECTED_NODE_COUNT,
        },
        "nodes": public_nodes,
        "exclusions": [
            "The fixture uses a private deterministic format, not GGUF.",
            "No subprocess or llama.cpp runtime is exercised by this browser replay.",
            (
                "No model quality, numerical equivalence, or cross-hardware "
                "compatibility is established."
            ),
        ],
    }
    _validate_site_evidence(payload, destination)
    _atomic_write_json(destination, payload)
    return payload


def _safe_member_name(name: str) -> None:
    member = PurePosixPath(name)
    has_drive_prefix = bool(member.parts and member.parts[0].endswith(":"))
    if (
        not name
        or "\\" in name
        or member.is_absolute()
        or ".." in member.parts
        or has_drive_prefix
    ):
        raise ReleaseCheckError(f"unsafe archive member: {name}")


def inspect_archives(archives: Iterable[Path]) -> dict[str, Any]:
    inventory: dict[str, Any] = {
        "schema": "modelbake.release-inventory.v1",
        "archives": [],
    }
    for archive in sorted(archives):
        members: list[dict[str, Any]] = []
        if archive.suffix == ".whl":
            with zipfile.ZipFile(archive) as package:
                for info in package.infolist():
                    _safe_member_name(info.filename)
                    if info.flag_bits & 0x1:
                        raise ReleaseCheckError(
                            f"encrypted wheel member is forbidden: {info.filename}"
                        )
                    file_type = (info.external_attr >> 16) & 0o170000
                    if file_type == 0o120000:
                        raise ReleaseCheckError(
                            f"wheel symlink is forbidden: {info.filename}"
                        )
                    members.append({"path": info.filename, "bytes": info.file_size})
                corrupt_member = package.testzip()
                if corrupt_member:
                    raise ReleaseCheckError(
                        f"wheel has a corrupt member: {corrupt_member}"
                    )
        elif archive.name.endswith(".tar.gz"):
            with tarfile.open(archive, mode="r:gz") as package:
                for info in package.getmembers():
                    _safe_member_name(info.name)
                    if info.issym() or info.islnk() or info.isdev():
                        raise ReleaseCheckError(
                            f"unsafe sdist member type: {info.name}"
                        )
                    if info.isfile():
                        extracted = package.extractfile(info)
                        if extracted is None:
                            raise ReleaseCheckError(
                                f"cannot read sdist member: {info.name}"
                            )
                        while extracted.read(1024 * 1024):
                            pass
                    members.append({"path": info.name, "bytes": info.size})
        else:
            raise ReleaseCheckError(f"unexpected distribution archive: {archive.name}")
        names = [member["path"] for member in members]
        has_metadata = any(name.endswith(".dist-info/METADATA") for name in names)
        if archive.suffix == ".whl" and not has_metadata:
            raise ReleaseCheckError(f"wheel has no METADATA: {archive.name}")
        if not any("modelbake/" in name for name in names):
            raise ReleaseCheckError(f"archive has no modelbake package: {archive.name}")
        if archive.suffix == ".whl":
            wheel_requirements = (
                "modelbake/baseline.py",
                "modelbake/cli.py",
                "modelbake/compare.py",
                "entry_points.txt",
                "RECORD",
            )
            missing = [
                value
                for value in wheel_requirements
                if not any(name.endswith(value) for name in names)
            ]
        else:
            sdist_requirements = (
                "action.yml",
                "docs/BASELINES.md",
                "docs/CI_INTEGRATION.md",
                "docs/EVIDENCE_MODEL.md",
                "docs/REAL_ACCEPTANCE.md",
                "examples/github/modelbake-release.yml",
                "LICENSE",
                "PKG-INFO",
                "README.md",
                "pyproject.toml",
                "scripts/generate_public_evidence.py",
                "scripts/release_check.py",
                "src/modelbake/cli.py",
            )
            missing = [
                value
                for value in sdist_requirements
                if not any(name.endswith(value) for name in names)
            ]
            forbidden = []
            for name in names:
                parts = PurePosixPath(name).parts
                if "site" in parts or ".integration" in parts:
                    forbidden.append(name)
            if forbidden:
                raise ReleaseCheckError(
                    "sdist contains excluded site or local integration files: "
                    f"{forbidden[:5]}"
                )
        if missing:
            raise ReleaseCheckError(
                f"archive {archive.name} is missing required members: {missing}"
            )
        inventory["archives"].append(
            {
                "file": archive.name,
                "bytes": archive.stat().st_size,
                "members": members,
            }
        )
    return inventory


def _metadata_version(data: bytes, *, label: str) -> str:
    try:
        message = email.parser.BytesParser().parsebytes(data)
    except (TypeError, ValueError) as exc:
        raise ReleaseCheckError(f"cannot parse {label} metadata: {exc}") from exc
    version = message.get("Version")
    if not version or "\r" in version or "\n" in version:
        raise ReleaseCheckError(f"{label} metadata has no valid Version")
    return version


def validate_distribution_parity(wheel: Path, sdist: Path) -> None:
    """Require wheel and sdist to carry identical, syntactically valid product code."""

    wheel_sources: dict[str, bytes] = {}
    wheel_metadata: list[bytes] = []
    with zipfile.ZipFile(wheel) as archive:
        for info in archive.infolist():
            name = PurePosixPath(info.filename)
            if len(name.parts) >= 2 and name.parts[0] == "modelbake" and name.suffix == ".py":
                relative = PurePosixPath(*name.parts[1:]).as_posix()
                if relative in wheel_sources:
                    raise ReleaseCheckError(f"duplicate wheel Python source: {relative}")
                wheel_sources[relative] = archive.read(info)
            if info.filename.endswith(".dist-info/METADATA"):
                wheel_metadata.append(archive.read(info))

    sdist_sources: dict[str, bytes] = {}
    sdist_metadata: list[bytes] = []
    with tarfile.open(sdist, mode="r:gz") as archive:
        for info in archive.getmembers():
            parts = PurePosixPath(info.name).parts
            if not info.isfile():
                continue
            extracted = archive.extractfile(info)
            if extracted is None:
                raise ReleaseCheckError(f"cannot read sdist member: {info.name}")
            if len(parts) >= 4 and parts[1:3] == ("src", "modelbake") and info.name.endswith(".py"):
                relative = PurePosixPath(*parts[3:]).as_posix()
                if relative in sdist_sources:
                    raise ReleaseCheckError(f"duplicate sdist Python source: {relative}")
                sdist_sources[relative] = extracted.read()
            elif len(parts) == 2 and parts[1] == "PKG-INFO":
                sdist_metadata.append(extracted.read())

    if not wheel_sources or not sdist_sources:
        raise ReleaseCheckError("wheel or sdist has no ModelBake Python source")
    if len(wheel_metadata) != 1 or len(sdist_metadata) != 1:
        raise ReleaseCheckError("wheel and sdist must each contain one version metadata record")
    wheel_version = _metadata_version(wheel_metadata[0], label="wheel")
    sdist_version = _metadata_version(sdist_metadata[0], label="sdist")
    if wheel_version != sdist_version:
        raise ReleaseCheckError(
            f"wheel and sdist versions differ: {wheel_version!r} != {sdist_version!r}"
        )
    for label, sources in (("wheel", wheel_sources), ("sdist", sdist_sources)):
        for relative, source in sources.items():
            try:
                compile(source.decode("utf-8"), f"modelbake/{relative}", "exec")
            except (SyntaxError, UnicodeError) as exc:
                raise ReleaseCheckError(
                    f"{label} Python source is invalid: modelbake/{relative}: {exc}"
                ) from exc
    if wheel_sources != sdist_sources:
        missing = sorted(set(wheel_sources) - set(sdist_sources))
        extra = sorted(set(sdist_sources) - set(wheel_sources))
        changed = sorted(
            path
            for path in set(wheel_sources) & set(sdist_sources)
            if wheel_sources[path] != sdist_sources[path]
        )
        raise ReleaseCheckError(
            "wheel and sdist ModelBake Python sources differ; "
            f"missing={missing}, extra={extra}, changed={changed}"
        )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def sync_site_downloads(archives: Iterable[Path], site_dist: Path) -> list[Path]:
    """Atomically copy distributions and refresh their public checksum manifest."""

    source_paths = sorted({Path(path) for path in archives})
    for source in source_paths:
        if source.is_symlink() or not source.is_file():
            raise ReleaseCheckError(f"distribution is not a regular file: {source}")
    sources = [path.resolve() for path in source_paths]
    wheels = [path for path in sources if path.suffix == ".whl"]
    sdists = [path for path in sources if path.name.endswith(".tar.gz")]
    if len(sources) != 2 or len(wheels) != 1 or len(sdists) != 1:
        raise ReleaseCheckError("site downloads require exactly one wheel and one sdist")
    if site_dist.is_symlink() or not site_dist.is_dir():
        raise ReleaseCheckError(f"site distribution path is unsafe: {site_dist}")
    downloads = site_dist / "downloads"
    if downloads.is_symlink():
        raise ReleaseCheckError(f"site downloads path may not be a symlink: {downloads}")
    if downloads.exists() and not downloads.is_dir():
        raise ReleaseCheckError(f"site downloads path is not a directory: {downloads}")
    downloads.mkdir(mode=0o700, exist_ok=True)

    existing: dict[str, Path] = {}
    for child in downloads.iterdir():
        if child.is_symlink() or not child.is_file():
            raise ReleaseCheckError(f"unexpected site downloads entry: {child}")
        if (
            child.suffix != ".whl"
            and not child.name.endswith(".tar.gz")
            and child.name != "SHA256SUMS"
        ):
            raise ReleaseCheckError(f"unexpected non-package site download: {child}")
        existing[child.name] = child

    temporary_files: list[Path] = []
    destinations: list[Path] = []
    try:
        for source in sources:
            descriptor, temporary_name = tempfile.mkstemp(
                prefix=f".{source.name}.", suffix=".sync", dir=downloads
            )
            temporary = Path(temporary_name)
            temporary_files.append(temporary)
            with os.fdopen(descriptor, "wb") as output_stream:
                with source.open("rb") as input_stream:
                    shutil.copyfileobj(input_stream, output_stream)
                output_stream.flush()
                os.fsync(output_stream.fileno())
            if sha256_file(temporary) != sha256_file(source):
                raise ReleaseCheckError(f"site download copy changed bytes: {source.name}")
            destination = downloads / source.name
            os.replace(temporary, destination)
            temporary_files.remove(temporary)
            destinations.append(destination)

        checksum_lines = [
            f"{sha256_file(path)}  {path.name}" for path in sorted(destinations)
        ]
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=".SHA256SUMS.", suffix=".sync", dir=downloads
        )
        temporary = Path(temporary_name)
        temporary_files.append(temporary)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write("\n".join(checksum_lines) + "\n")
            stream.flush()
            os.fsync(stream.fileno())
        checksum_destination = downloads / "SHA256SUMS"
        os.replace(temporary, checksum_destination)
        temporary_files.remove(temporary)

        current_names = {source.name for source in sources} | {"SHA256SUMS"}
        for stale_name, stale_path in existing.items():
            if stale_name not in current_names:
                stale_path.unlink()
    finally:
        for temporary in temporary_files:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass
    return sorted(destinations)


def sync_release_distributions(
    archives: Iterable[Path], release_dist: Path
) -> list[Path]:
    """Replace the conventional dist/ contents with the exact inspected pair."""

    source_paths = sorted({Path(path) for path in archives})
    sources = [path.resolve(strict=True) for path in source_paths]
    if (
        len(sources) != 2
        or len([path for path in sources if path.suffix == ".whl"]) != 1
        or len([path for path in sources if path.name.endswith(".tar.gz")]) != 1
    ):
        raise ReleaseCheckError("release dist requires exactly one wheel and one sdist")
    if release_dist.is_symlink():
        raise ReleaseCheckError(f"release dist path may not be a symlink: {release_dist}")
    if release_dist.exists() and not release_dist.is_dir():
        raise ReleaseCheckError(f"release dist path is not a directory: {release_dist}")
    release_dist.mkdir(mode=0o700, exist_ok=True)

    existing: dict[str, Path] = {}
    for child in release_dist.iterdir():
        if child.is_symlink() or not child.is_file():
            raise ReleaseCheckError(f"unexpected release dist entry: {child}")
        if child.suffix != ".whl" and not child.name.endswith(".tar.gz"):
            raise ReleaseCheckError(f"unexpected non-package release dist entry: {child}")
        existing[child.name] = child

    temporary_files: list[Path] = []
    destinations: list[Path] = []
    try:
        for source in sources:
            descriptor, temporary_name = tempfile.mkstemp(
                prefix=f".{source.name}.", suffix=".sync", dir=release_dist
            )
            temporary = Path(temporary_name)
            temporary_files.append(temporary)
            with os.fdopen(descriptor, "wb") as output_stream:
                with source.open("rb") as input_stream:
                    shutil.copyfileobj(input_stream, output_stream)
                output_stream.flush()
                os.fsync(output_stream.fileno())
            if sha256_file(temporary) != sha256_file(source):
                raise ReleaseCheckError(f"release dist copy changed bytes: {source.name}")
            destination = release_dist / source.name
            os.replace(temporary, destination)
            temporary_files.remove(temporary)
            destinations.append(destination)

        current_names = {source.name for source in sources}
        for stale_name, stale_path in existing.items():
            if stale_name not in current_names:
                stale_path.unlink()
    finally:
        for temporary in temporary_files:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass
    return sorted(destinations)


def write_checksums(stage: Path, files: Iterable[Path]) -> Path:
    entries: list[str] = []
    for path in sorted({item.resolve() for item in files}):
        try:
            relative = path.relative_to(stage.resolve())
        except ValueError as exc:
            raise ReleaseCheckError(
                f"checksum target is outside staging: {path}"
            ) from exc
        entries.append(f"{sha256_file(path)}  {relative.as_posix()}")
    if not entries:
        raise ReleaseCheckError("refusing to write an empty checksum manifest")
    destination = stage / "SHA256SUMS"
    destination.write_text("\n".join(entries) + "\n", encoding="utf-8")
    return destination


def create_publish_bundle(
    stage: Path,
    archives: Iterable[Path],
    inventory: Path,
    public_evidence: Path,
) -> Path:
    """Create the only CI-uploadable bundle from already validated public files."""

    publish = stage / "publish"
    if publish.exists() or publish.is_symlink():
        raise ReleaseCheckError("publish bundle path must not already exist")
    publish.mkdir(mode=0o700)
    sources = [*sorted(archives), inventory, public_evidence]
    destinations: list[Path] = []
    seen: set[str] = set()
    for source in sources:
        source = Path(source)
        if source.is_symlink() or not source.is_file():
            raise ReleaseCheckError(f"publish source is not a regular file: {source}")
        name = "public-real-evidence.json" if source == public_evidence else source.name
        if name in seen or "/" in name or "\\" in name:
            raise ReleaseCheckError(f"publish filename is unsafe or duplicated: {name}")
        seen.add(name)
        destination = publish / name
        shutil.copyfile(source, destination)
        if sha256_file(source) != sha256_file(destination):
            raise ReleaseCheckError(f"publish copy changed bytes: {name}")
        destinations.append(destination)
    if len([path for path in destinations if path.suffix == ".whl"]) != 1:
        raise ReleaseCheckError("publish bundle must contain exactly one wheel")
    if len([path for path in destinations if path.name.endswith(".tar.gz")]) != 1:
        raise ReleaseCheckError("publish bundle must contain exactly one sdist")
    if {path.name for path in destinations if path.suffix == ".json"} != {
        "archive-inventory.json",
        "public-real-evidence.json",
    }:
        raise ReleaseCheckError("publish bundle has an unexpected JSON inventory")
    checksums = write_checksums(publish, destinations)
    listed = {
        line.split("  ", 1)[1]
        for line in checksums.read_text(encoding="utf-8").splitlines()
    }
    if listed != {path.name for path in destinations}:
        raise ReleaseCheckError("publish checksums are not exhaustive")
    return publish


def _python_env() -> dict[str, str]:
    env = os.environ.copy()
    existing = env.get("PYTHONPATH")
    source = os.fspath(ROOT / "src")
    env["PYTHONPATH"] = source if not existing else os.pathsep.join((source, existing))
    return env


def _require_tool(name: str, explanation: str) -> str:
    executable = shutil.which(name)
    if executable is None:
        raise ReleaseCheckError(f"{name} is required {explanation}")
    return executable


def _compile_python() -> None:
    with tempfile.TemporaryDirectory(prefix="modelbake-compile-cache-") as temporary:
        env = os.environ.copy()
        env["PYTHONPYCACHEPREFIX"] = temporary
        run_command(
            [sys.executable, "-m", "compileall", "-q", "-f", "src", "scripts"],
            env=env,
            label="compile Python sources",
        )


def _run_fixture_acceptance(
    stage: Path,
    env: dict[str, str],
    *,
    demo_evidence_path: Path | None = None,
) -> list[Path]:
    acceptance = stage / "acceptance"
    cache = acceptance / "cache"
    cold = acceptance / "cold"
    warm = acceptance / "warm"
    recipe = ROOT / "examples" / "modelbake.fixture.yaml"
    for run_dir, label in ((cold, "cold fixture build"), (warm, "warm fixture build")):
        run_command(
            [
                sys.executable,
                "-m",
                "modelbake.cli",
                "build",
                recipe,
                "--run-dir",
                run_dir,
                "--cache-dir",
                cache,
            ],
            env=env,
            label=label,
        )
    cold_manifest = cold / "manifest.json"
    warm_manifest = warm / "manifest.json"
    _load_successful_manifest(cold_manifest, warm=False)
    _load_successful_manifest(warm_manifest, warm=True)
    reports = stage / "reports"
    reports.mkdir()
    generated: list[Path] = [cold_manifest, warm_manifest]
    for manifest, name in ((cold_manifest, "cold.html"), (warm_manifest, "warm.html")):
        verification = run_command(
            [
                sys.executable,
                "-m",
                "modelbake.cli",
                "verify",
                manifest,
                "--allow-artifact-root",
                cache,
                "--json",
            ],
            env=env,
            label=f"verify {name.removesuffix('.html')} manifest",
        )
        verification_payload = _parse_command_json(verification, f"verify {name}")
        if verification_payload.get("ok") is not True or verification_payload.get(
            "checked"
        ) != EXPECTED_NODE_COUNT:
            raise ReleaseCheckError(f"verify {name} did not check every fixture artifact")
        report = reports / name
        run_command(
            [
                sys.executable,
                "-m",
                "modelbake.cli",
                "report",
                manifest,
                "--html",
                report,
            ],
            env=env,
            label=f"render {name}",
        )
        validate_generated_report(report)
        generated.append(report)
    comparison_result = run_command(
        [
            sys.executable,
            "-m",
            "modelbake.cli",
            "compare",
            cold_manifest,
            warm_manifest,
            "--json",
        ],
        env=env,
        label="compare cold and warm fixture manifests",
    )
    comparison_payload = _parse_command_json(comparison_result, "fixture comparison")
    _require_warm_comparison(comparison_payload, "fixture comparison")
    comparison_path = reports / "fixture-comparison.json"
    comparison_path.write_text(
        json.dumps(comparison_payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    generated.append(comparison_path)
    if demo_evidence_path is not None:
        generate_demo_evidence(cold_manifest, warm_manifest, demo_evidence_path)
    return generated


def validate_generated_report(path: Path) -> None:
    try:
        content = path.read_text(encoding="utf-8").lower()
    except (OSError, UnicodeError) as exc:
        raise ReleaseCheckError(f"cannot read generated report {path}: {exc}") from exc
    required = ("<!doctype html>", "modelbake", "truth boundary", "succeeded")
    missing = [token for token in required if token not in content]
    if missing:
        raise ReleaseCheckError(f"generated report {path} is missing {missing}")


def _build_distributions(stage: Path) -> list[Path]:
    packages = stage / "packages"
    packages.mkdir()
    build_env = os.environ.copy()
    build_env["SOURCE_DATE_EPOCH"] = REPRODUCIBLE_BUILD_EPOCH
    run_command(
        [sys.executable, "-m", "build", "--outdir", packages, ROOT],
        env=build_env,
        label="build wheel and source distribution",
    )
    wheels = sorted(packages.glob("*.whl"))
    sdists = sorted(packages.glob("*.tar.gz"))
    if len(wheels) != 1 or len(sdists) != 1:
        raise ReleaseCheckError(
            f"expected one wheel and one sdist, found {len(wheels)} and {len(sdists)}"
        )
    return [*wheels, *sdists]


def _smoke_install(distribution: Path) -> None:
    distribution = distribution.resolve(strict=True)
    with tempfile.TemporaryDirectory(prefix="modelbake-wheel-smoke-") as temporary:
        temporary_root = Path(temporary)
        environment = temporary_root / "venv"
        work = temporary_root / "unrelated-cwd"
        work.mkdir()
        _say("create clean wheel smoke-test environment")
        try:
            venv.EnvBuilder(with_pip=True, clear=False).create(environment)
        except (OSError, subprocess.SubprocessError) as exc:
            uv = shutil.which("uv")
            if uv is None:
                raise ReleaseCheckError(
                    f"could not create clean virtual environment: {exc}"
                ) from exc
            _say(f"stdlib venv creation failed ({exc}); retry with uv")
            run_command(
                [
                    uv,
                    "venv",
                    "--clear",
                    "--seed",
                    "--python",
                    sys.executable,
                    environment,
                ],
                cwd=work,
                label="create clean wheel smoke-test environment with uv",
            )
        if os.name == "nt":
            python = environment / "Scripts" / "python.exe"
            command = environment / "Scripts" / "modelbake.exe"
        else:
            python = environment / "bin" / "python"
            command = environment / "bin" / "modelbake"
        run_command(
            [
                python,
                "-m",
                "pip",
                "install",
                "--disable-pip-version-check",
                distribution,
            ],
            cwd=work,
            label=f"install {distribution.name} into clean environment",
        )
        if not command.is_file():
            raise ReleaseCheckError(
                f"{distribution.name} did not install the modelbake console entry point"
            )
        smoke_env = os.environ.copy()
        smoke_env.pop("PYTHONPATH", None)
        smoke_env.pop("PYTHONHOME", None)
        smoke_env["PYTHONNOUSERSITE"] = "1"
        run_command(
            [command, "--help"],
            cwd=work,
            env=smoke_env,
            label="smoke console entry point",
        )

        tour_root = work / "tour"
        tour_result = run_command(
            [command, "tour", "--run-root", tour_root],
            cwd=work,
            env=smoke_env,
            label="installed-package one-command tour",
        )
        if "RELEASE DIFF" not in tour_result.stdout or "quantize-q8" not in tour_result.stdout:
            raise ReleaseCheckError("installed-package tour did not show the release diff")
        _load_story_manifest(tour_root / "accepted" / "manifest.json", candidate=False)
        _load_story_manifest(tour_root / "candidate" / "manifest.json", candidate=True)

        cache = work / "cache"
        cold = work / "cold"
        warm = work / "warm"
        for run_dir, story, label in (
            (cold, "baseline", "installed-package Q4 baseline story"),
            (warm, "candidate", "installed-package Q4+Q8 candidate story"),
        ):
            run_command(
                [
                    command,
                    "demo",
                    "--story",
                    story,
                    "--run-dir",
                    run_dir,
                    "--cache-dir",
                    cache,
                ],
                cwd=work,
                env=smoke_env,
                label=label,
            )

        cold_manifest = cold / "manifest.json"
        warm_manifest = warm / "manifest.json"
        cold_payload = _load_story_manifest(cold_manifest, candidate=False)
        _load_story_manifest(warm_manifest, candidate=True)
        for manifest, expected, label in (
            (cold_manifest, 4, "installed-package baseline verification"),
            (warm_manifest, 6, "installed-package candidate verification"),
        ):
            verification = _parse_command_json(
                run_command(
                    [
                        command,
                        "verify",
                        manifest,
                        "--allow-artifact-root",
                        cache,
                        "--json",
                    ],
                    cwd=work,
                    env=smoke_env,
                    label=label,
                ),
                label,
            )
            if verification.get("ok") is not True or verification.get(
                "checked"
            ) != expected:
                raise ReleaseCheckError(f"{label} did not check every artifact")

        report = work / "cold-report.html"
        run_command(
            [command, "report", cold_manifest, "--html", report],
            cwd=work,
            env=smoke_env,
            label="installed-wheel HTML report",
        )
        validate_generated_report(report)

        comparison = _parse_command_json(
            run_command(
                [command, "compare", cold_manifest, warm_manifest, "--json"],
                cwd=work,
                env=smoke_env,
                label="installed-wheel manifest comparison",
            ),
            "installed-wheel manifest comparison",
        )
        _require_story_comparison(comparison, "installed-package story comparison")

        baseline_store = work / "baselines"
        baseline_name = "release-smoke"
        initial_review = work / "cold-review.json"
        reviewed = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "review",
                    cold_manifest,
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--review",
                    initial_review,
                    "--allow-artifact-root",
                    cache,
                    "--initial",
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel initial release review",
            ),
            "installed-wheel initial release review",
        )
        if reviewed.get("initial") is not True or reviewed.get(
            "verified_artifacts"
        ) != 4:
            raise ReleaseCheckError("installed-wheel initial review is incomplete")
        accepted = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "accept",
                    cold_manifest,
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--allow-artifact-root",
                    cache,
                    "--note",
                    "release gate acceptance",
                    "--review",
                    initial_review,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel baseline acceptance",
            ),
            "installed-wheel baseline acceptance",
        )
        if accepted.get("created") is not True or accepted.get(
            "verified_artifacts"
        ) != 4:
            raise ReleaseCheckError("installed-wheel baseline acceptance is incomplete")

        current = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "current",
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel current baseline",
            ),
            "installed-wheel current baseline",
        )
        if current.get("run_id") != cold_payload.get("run_id"):
            raise ReleaseCheckError("installed-wheel current baseline changed run identity")

        ledger = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "verify",
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel baseline ledger verification",
            ),
            "installed-wheel baseline ledger verification",
        )
        if ledger.get("decisions") != 1:
            raise ReleaseCheckError("installed-wheel baseline ledger is incomplete")

        baseline_comparison = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "compare",
                    warm_manifest,
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel baseline comparison",
            ),
            "installed-wheel baseline comparison",
        )
        _require_story_comparison(
            baseline_comparison, "installed-package baseline comparison"
        )

        warm_review = work / "warm-review.json"
        reviewed_warm = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "review",
                    warm_manifest,
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--review",
                    warm_review,
                    "--allow-artifact-root",
                    cache,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel successor release review",
            ),
            "installed-wheel successor release review",
        )
        if reviewed_warm.get("predecessor_decision_digest") != accepted.get(
            "decision_digest"
        ):
            raise ReleaseCheckError("installed-wheel review did not bind its predecessor")
        accepted_warm = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "accept",
                    warm_manifest,
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--allow-artifact-root",
                    cache,
                    "--review",
                    warm_review,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel reviewed successor acceptance",
            ),
            "installed-wheel reviewed successor acceptance",
        )
        if accepted_warm.get("created") is not True:
            raise ReleaseCheckError("installed-wheel successor was not accepted")
        checked_warm = _parse_command_json(
            run_command(
                [
                    command,
                    "baseline",
                    "check",
                    warm_manifest,
                    "--store",
                    baseline_store,
                    "--name",
                    baseline_name,
                    "--allow-artifact-root",
                    cache,
                    "--json",
                ],
                cwd=work,
                env=smoke_env,
                label="installed-wheel exact accepted baseline check",
            ),
            "installed-wheel exact accepted baseline check",
        )
        if checked_warm.get("current") is not True or checked_warm.get(
            "verified_artifacts"
        ) != 6:
            raise ReleaseCheckError("installed-wheel current baseline check is incomplete")


def release_check(stage_arg: Path, *, bootstrap_real_acceptance: bool = False) -> Path:
    stage = prepare_stage(stage_arg)
    env = _python_env()
    _say(f"staging directory: {stage}")

    run_command(
        [sys.executable, "-m", "pytest", "tests"],
        env=env,
        label="run source test suite",
    )
    ruff = shutil.which("ruff")
    if ruff:
        run_command([ruff, "check", "src", "tests", "scripts"], label="run Ruff")
    else:
        _say("Ruff not installed; skipped locally (the release workflow installs it)")

    _compile_python()

    acceptance_files = _run_fixture_acceptance(
        stage,
        env,
        demo_evidence_path=ROOT / "site" / "dist" / "demo-evidence.json",
    )
    archives = _build_distributions(stage)
    inventory = inspect_archives(archives)
    wheel = next(path for path in archives if path.suffix == ".whl")
    sdist = next(path for path in archives if path.name.endswith(".tar.gz"))
    validate_distribution_parity(wheel, sdist)
    inventory_path = stage / "archive-inventory.json"
    inventory_path.write_text(
        json.dumps(inventory, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    synced_release = sync_release_distributions(archives, ROOT / "dist")
    _say(
        "synced inspected release distributions: "
        + ", ".join(path.name for path in synced_release)
    )
    synced_downloads = sync_site_downloads(archives, ROOT / "site" / "dist")
    _say(
        "synced inspected site downloads: "
        + ", ".join(path.name for path in synced_downloads)
    )

    real_evidence = ROOT / "site" / "dist" / "real-evidence.json"
    if bootstrap_real_acceptance:
        _say(
            "BOOTSTRAP ONLY: skipped public real evidence validation; "
            "this is not a final release gate"
        )
    else:
        validate_public_evidence(real_evidence, archives, env)

    node = _require_tool("node", "to perform JavaScript syntax validation")

    def check_javascript(path: Path) -> None:
        run_command([node, "--check", path], label=f"validate JavaScript: {path.name}")

    assets = validate_site(
        ROOT / "site" / "dist",
        javascript_checker=check_javascript,
        validate_real_evidence=not bootstrap_real_acceptance,
    )
    _say(f"validated site HTML, JSON, JavaScript, and {len(assets)} asset files")

    _smoke_install(wheel)
    _smoke_install(sdist)
    checksums = write_checksums(stage, [*acceptance_files, *archives, inventory_path])
    if bootstrap_real_acceptance:
        _say(
            "bootstrap candidate prepared; real evidence remains required for the "
            f"final gate; checksums: {checksums}"
        )
    else:
        publish = create_publish_bundle(stage, archives, inventory_path, real_evidence)
        _say(f"release candidate passed; public bundle: {publish}; checksums: {checksums}")
    return stage


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Build and verify a local ModelBake release candidate."
    )
    parser.add_argument(
        "--staging-dir",
        type=Path,
        default=DEFAULT_STAGE,
        help=f"artifact directory (default: {DEFAULT_STAGE})",
    )
    parser.add_argument(
        "--bootstrap-real-acceptance",
        action="store_true",
        help=(
            "prepare exact packages for a fresh real acceptance run without "
            "claiming that the final release gate passed"
        ),
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        release_check(
            args.staging_dir,
            bootstrap_real_acceptance=args.bootstrap_real_acceptance,
        )
    except (
        ReleaseCheckError,
        OSError,
        ValueError,
        zipfile.BadZipFile,
        tarfile.TarError,
    ) as exc:
        print(f"[release-check] FAILED: {exc}", file=sys.stderr, flush=True)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
